# Generated by Django 6.0.1 on 2026-02-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Circuit', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('qubits', models.IntegerField(default=5)),
                ('gates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_circuits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quantum Circuit',
                'verbose_name_plural': 'Quantum Circuits',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_vector', models.JSONField()),
                ('probability_distribution', models.JSONField()),
                ('measurements', models.JSONField()),
                ('execution_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qubit_count', models.IntegerField()),
                ('gate_count', models.IntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='api.quantumcircuit')),
            ],
            options={
                'verbose_name': 'Simulation Result',
                'verbose_name_plural': 'Simulation Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
