# Generated by Django 6.0.1 on 2026-03-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quantumcircuit_simulationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantumcircuit',
            name='classical_bits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantumcircuit',
            name='custom_gates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='shots',
            field=models.IntegerField(default=1000),
        ),
    ]
