import time
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
import json


class PythonCodeGenerationView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        """
        Generate Python code from quantum circuit configuration.
        """
        start_time = time.time()

        try:
            circuit_data = request.data.get('circuit', {})

            if not circuit_data:
                return Response({
                    'success': False,
                    'error': 'No circuit configuration provided'
                }, status=status.HTTP_400_BAD_REQUEST)

            qubits = circuit_data.get('qubits', 5)
            gates = circuit_data.get('gates', [])
            description = circuit_data.get('description', 'Quantum Circuit')

            # Generate Python code using Qiskit
            code = self.generate_python_code(qubits, gates, description)

            response = {
                'success': True,
                'data': {
                    'python_code': code,
                    'execution_time': round(time.time() - start_time, 3)
                }
            }

            return Response(response, status=status.HTTP_200_OK)

        except Exception as e:
            return Response({
                'success': False,
                'error': str(e)
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def generate_python_code(self, qubits, gates, description):
        """
        Generate Python code from circuit configuration.
        """
        code = f"""# Quantum Circuit: {description}
# Generated by QuantumSim API
from qiskit import QuantumCircuit, Aer, execute

# Create quantum circuit with {qubits} qubits
{"qc = QuantumCircuit(" + str(qubits) + ", " + str(qubits) + ")  # With classical bits for measurement" if any(g['gate'] == 'Measure' for g in gates) else "qc = QuantumCircuit(" + str(qubits) + ")"}

"""

        # Add imports for needed gates
        gate_types = set(g['gate'] for g in gates)
        if 'RX' in gate_types or 'RY' in gate_types or 'RZ' in gate_types or 'P' in gate_types:
            code += "# Import math for angle calculations\nimport math\n\n"

        # Process gates
        time_slots = {}
        for gate in sorted(gates, key=lambda x: x['time']):
            qubit_index = gate['qubitIndex']
            gate_type = gate['gate']
            params = gate.get('params', {})

            time_slot = gate['time']
            if time_slot not in time_slots:
                time_slots[time_slot] = []
            time_slots[time_slot].append((qubit_index, gate_type, params))

        for time_slot in sorted(time_slots.keys()):
            code += f"# Time slot {time_slot + 1}\n"
            for qubit_index, gate_type, params in time_slots[time_slot]:
                if gate_type == 'H':
                    code += f"qc.h({qubit_index})\n"
                elif gate_type == 'X':
                    code += f"qc.x({qubit_index})\n"
                elif gate_type == 'Y':
                    code += f"qc.y({qubit_index})\n"
                elif gate_type == 'Z':
                    code += f"qc.z({qubit_index})\n"
                elif gate_type == 'S':
                    code += f"qc.s({qubit_index})\n"
                elif gate_type == 'T':
                    code += f"qc.t({qubit_index})\n"
                elif gate_type == 'Tdg':
                    code += f"qc.tdg({qubit_index})\n"
                elif gate_type == 'Sdg':
                    code += f"qc.sdg({qubit_index})\n"
                elif gate_type == 'RX':
                    angle = params.get('angle', 0)
                    code += f"qc.rx({angle}, {qubit_index})\n"
                elif gate_type == 'RY':
                    angle = params.get('angle', 0)
                    code += f"qc.ry({angle}, {qubit_index})\n"
                elif gate_type == 'RZ':
                    angle = params.get('angle', 0)
                    code += f"qc.rz({angle}, {qubit_index})\n"
                elif gate_type == 'P':
                    phase = params.get('phase', 0)
                    code += f"qc.p({phase}, {qubit_index})\n"
                elif gate_type == 'CNOT':
                    target = params.get('target', 1)
                    code += f"qc.cx({qubit_index}, {target})\n"
                elif gate_type == 'CZ':
                    target = params.get('target', 1)
                    code += f"qc.cz({qubit_index}, {target})\n"
                elif gate_type == 'SWAP':
                    target = params.get('target', 1)
                    code += f"qc.swap({qubit_index}, {target})\n"
                elif gate_type == 'Measure':
                    classical_bit = params.get('classicalBit', qubit_index)
                    code += f"qc.measure({qubit_index}, {classical_bit})\n"
                elif gate_type == 'I':
                    code += f"qc.id({qubit_index})\n"

            code += "\n"

        # Add visualization and simulation code
        code += """# ------------------------------
# Simulation and Visualization
# ------------------------------
print("Circuit Diagram:")
print(qc.draw())

# Simulate the circuit
simulator = Aer.get_backend('qasm_simulator')
result = execute(qc, simulator, shots=1024).result()
counts = result.get_counts()

print("\\nMeasurement Results:")
print(counts)

# Visualize results
try:
    from qiskit.visualization import plot_histogram
    import matplotlib.pyplot as plt
    plot_histogram(counts).savefig('circuit_results.png')
    print("\\nResults saved to 'circuit_results.png'")
    plt.show()
except ImportError:
    print("\\nQiskit visualization tools not available. Install with: pip install qiskit-terra[visualization]")
except Exception as e:
    print(f"\\nError visualizing results: {e}")
"""

        return code


class QASMGenerationView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        """
        Generate OpenQASM code from quantum circuit configuration.
        """
        start_time = time.time()

        try:
            circuit_data = request.data.get('circuit', {})

            if not circuit_data:
                return Response({
                    'success': False,
                    'error': 'No circuit configuration provided'
                }, status=status.HTTP_400_BAD_REQUEST)

            qubits = circuit_data.get('qubits', 5)
            gates = circuit_data.get('gates', [])
            description = circuit_data.get('description', 'Quantum Circuit')

            # Generate QASM code
            qasm_code = self.generate_qasm_code(qubits, gates, description)

            response = {
                'success': True,
                'data': {
                    'qasm_code': qasm_code,
                    'execution_time': round(time.time() - start_time, 3)
                }
            }

            return Response(response, status=status.HTTP_200_OK)

        except Exception as e:
            return Response({
                'success': False,
                'error': str(e)
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def generate_qasm_code(self, qubits, gates, description):
        """
        Generate OpenQASM code from circuit configuration.
        """
        qasm = f"""// Quantum Circuit: {description}
// Generated by QuantumSim API
OPENQASM 2.0;
include "qelib1.inc";

"""

        # Add quantum and classical registers
        has_measure = any(g['gate'] == 'Measure' for g in gates)
        qasm += f"qreg q[{qubits}];\n"
        if has_measure:
            qasm += f"creg c[{qubits}];\n"
        qasm += "\n"

        # Process gates
        time_slots = {}
        for gate in sorted(gates, key=lambda x: x['time']):
            qubit_index = gate['qubitIndex']
            gate_type = gate['gate']
            params = gate.get('params', {})

            time_slot = gate['time']
            if time_slot not in time_slots:
                time_slots[time_slot] = []
            time_slots[time_slot].append((qubit_index, gate_type, params))

        for time_slot in sorted(time_slots.keys()):
            qasm += f"// Time slot {time_slot + 1}\n"
            for qubit_index, gate_type, params in time_slots[time_slot]:
                if gate_type == 'H':
                    qasm += f"h q[{qubit_index}];\n"
                elif gate_type == 'X':
                    qasm += f"x q[{qubit_index}];\n"
                elif gate_type == 'Y':
                    qasm += f"y q[{qubit_index}];\n"
                elif gate_type == 'Z':
                    qasm += f"z q[{qubit_index}];\n"
                elif gate_type == 'S':
                    qasm += f"s q[{qubit_index}];\n"
                elif gate_type == 'T':
                    qasm += f"t q[{qubit_index}];\n"
                elif gate_type == 'Tdg':
                    qasm += f"tdg q[{qubit_index}];\n"
                elif gate_type == 'Sdg':
                    qasm += f"sdg q[{qubit_index}];\n"
                elif gate_type == 'RX':
                    angle = params.get('angle', 0)
                    qasm += f"rx({angle}) q[{qubit_index}];\n"
                elif gate_type == 'RY':
                    angle = params.get('angle', 0)
                    qasm += f"ry({angle}) q[{qubit_index}];\n"
                elif gate_type == 'RZ':
                    angle = params.get('angle', 0)
                    qasm += f"rz({angle}) q[{qubit_index}];\n"
                elif gate_type == 'P':
                    phase = params.get('phase', 0)
                    qasm += f"p({phase}) q[{qubit_index}];\n"
                elif gate_type == 'CNOT':
                    target = params.get('target', 1)
                    qasm += f"cx q[{qubit_index}], q[{target}];\n"
                elif gate_type == 'CZ':
                    target = params.get('target', 1)
                    qasm += f"cz q[{qubit_index}], q[{target}];\n"
                elif gate_type == 'SWAP':
                    target = params.get('target', 1)
                    qasm += f"swap q[{qubit_index}], q[{target}];\n"
                elif gate_type == 'Measure':
                    classical_bit = params.get('classicalBit', qubit_index)
                    qasm += f"measure q[{qubit_index}] -> c[{classical_bit}];\n"
                elif gate_type == 'I':
                    qasm += f"id q[{qubit_index}];\n"

            qasm += "\n"

        return qasm
